### ISSUE TITLE
CoC: Rephrase Ground Rule 3

### ISSUE THREAD

**Issue by CovenEsme** [Quoth-the-Bot-Nevermore/Corvid#2]
I don't like having (multiple) example(s) of "I need time off because X thing happened". Could this be rephrased more generally as:

For example, if a person says they can't do, require assistance to do or need more time to do [a thing] because of [a reason]; accept that statement at face value.

**Comment by ghost** [comment]
As discussed, I am fully aligned with this change.

**Comment by UnseenUniverse** [comment]
Makes sense to me! I suggested the extra example because I thought having the one didn't make it entirely clear. Being more general works better. All for the change.

**Comment by ghost** [comment]
@tertu-m Any thoughts before @elliebeph makes the change?

**Comment by CovenEsme** [comment]
Issue discussed in Discord - updating CoC to match.
